### ISSUE TITLE
Panics on color unwrap

### ISSUE THREAD

**Issue by nicholasday** [Keats/dbmigrate#22]
I'm running dbmigrate on a server with Python's Fabric library and I get this:

[174.138.34.126] out: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ColorOutOfRange', /checkout/src/libcore/result.rs:860
[174.138.34.126] out: note: Run with `RUST_BACKTRACE=1` for a backtrace.

I solved it by sshing in and running dbmigrate manually, but it would be nice to be able to run dbmigrate from Fabric.

Any ideas?

**Comment by Keats** [comment]
ah I will need to check for errors on https://github.com/Keats/dbmigrate/blob/master/dbmigrate/src/print.rs#L8 and line 16 rather than assuming i can use the colours

**Comment by Keats** [comment]
Can you try to build the version in master to see if it's fixed?

**Comment by nicholasday** [comment]
Yep, it's fixed! Thank you!
