### ISSUE TITLE
Allow specifying schema for migration table in postgres

### ISSUE THREAD

**Issue by hobofan** [Keats/dbmigrate#23]
Right now `dbmigrate` creates its `__dbmigrate_table` without specifying a schema, which by default will use the `public` schema.

In my use-case where I have `schema1` and `schema2` for two different projects. When I now use `dbmigrate`, the migrations of both projects try to use `public.__dbmigrate_table`, which causes them to mix up.

To avoid that, it would be nice to be able to specify a schema where `dbmigrate` looks for the migration table so that both migration tables can live separately in their respective schemas.

**Comment by hobofan** [comment]
I have a quick and dirty implementation of it up in my fork: https://github.com/hobofan/dbmigrate/tree/dirty_schema

@Keats If you think that this feature is worth being in upstream, I'd be happy to write up a PR with a more proper implementation. :)

**Comment by Keats** [comment]
Hmm I don't know if the libraries allow it but is it possible to specify it in the URL?

Postgres has `currentSchema` for this usecase I believe so `postgres://pg@localhost:5777/migrate?currentSchema=schema1` should do it (haven't tested).

**Comment by hobofan** [comment]
I checked, and the rust postgres crate does not support a `currentSchema`, and I'm not sure if it should.

From what I could gather `currentSchema` is a JDBC specific parameter, and is not on the list of recognized keywords: https://www.postgresql.org/docs/9.5/static/libpq-connect.html#LIBPQ-CONNSTRING

However I just saw that there is a `options` key, which could maybe allow me to specify a `search_path`. I'll try that and report back.

**Comment by hobofan** [comment]
Nope, doesn't seem to work. I've also found no reference of somebody else (ab)using the `options` key for that purpose.

**Comment by hobofan** [comment]
Seems that I just didn't use the right encoding. There is a blog post concerning Diesel using the same trick: http://yakshav.es/using-diesel-with-a-postgres-schema/

**Comment by Keats** [comment]
I'll add that to the docs!
