### ISSUE TITLE
Support multiple directories for migrations

### ISSUE THREAD

**Issue by Unmoving** [Keats/dbmigrate#27]
Consider the following folder structure:

`migrations`
`migrations/base`
`migrations/dummy_data`

Now, depending on some input either only migration files in `base` are to be executed or also the ones that insert some "dummy data".

From the top of my head there are two options to solve a situation like that:

1) Either make https://github.com/Keats/dbmigrate/blob/master/dbmigrate-lib/src/files.rs#L94 recursive
2) Allow multiple folders to be passed to the function

The workaround is copying everything from base also to `dummy_data` which is not really nice.

I wanted to discuss this, before starting any work.

**Comment by Keats** [comment]
I don't think it really make senses, fixtures are not migrations and are not meant to be handled by dbmigrate. You can load fixtures directly with psql or other cli tool if it's in a sql format

**Comment by Unmoving** [comment]
Point taken.

Generally splitting up into multiple different folders probably doesn't make sense due to the numbering which has to be kept in sync over multiple directories then.
