### ISSUE TITLE
Publishing a new release

### ISSUE THREAD

**Issue by chinedufn** [Keats/dbmigrate#45]
Hey!

I see that a few years ago `dbmigrate` used to provide release binaries in the GitHub repo.

Any reason for the stop - or was it just a hassle?

Any chance of publishing a new release with a recent version - if not I can totally just host my own somewhere - so it's really not an issue if it's a hassle.

Cheers!

**Comment by Keats** [comment]
Right now I only publish it in crates.io
I don't use it so not really worth the time setting up the publish pipeline

**Comment by chinedufn** [comment]
Gotcha!

If for some reason you ever want to in the future - `rust-analyzer` has an easy one to copy-paste-modify https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/release.yaml .

Just linking for completeness - totally not expecting you to publish releases when you don't need them. I'd offer to PR but debugging a deployment CI on someone elses repo would probably be a hassle ...

So - thanks for explaining - cheers!
