### ISSUE TITLE
Multiple migrations with the same number

### ISSUE THREAD

**Issue by chinedufn** [Keats/dbmigrate#47]
## Background

Say there are two developers named Jane and Rob working on the same codebase.

#### Main Branch

```
0001.first-migration.up.sql
0001.first-migration.down.sql
```

#### Jane's branch

```
0001.first-migration.up.sql
0001.first-migration.down.sql
0002.janes-migration.up.sql
0002.janes-migration.down.sql
```

#### Rob's branch

```
0001.first-migration.up.sql
0001.first-migration.down.sql
0002.robs-migration.up.sql
0002.robs-migration.down.sql
```

#### Merged

After Jane and Rob merge their branches into the main branch, the main branch looks like this:

```
0001.first-migration.up.sql
0001.first-migration.down.sql
0002.janes-migration.up.sql
0002.janes-migration.down.sql
0002.robs-migration.up.sql
0002.robs-migration.down.sql
```

## The Problem

Right now `dbmigrate` does not return an error in this case, which can lead to:

- Not realizing that a migration never actually got ran
- When migrating up a different migrations might run than when migrating down. 
  - For example when migrating up `janes-migration.up.sql` might run, but when migrating down `robs-migration.down.sql` might run.

## Potential Fix

Make `dbmigrate` return an error if there are two or more migrations that have the same number.

---

If I PR a fix can you merge it and deploy a new version?

Cheers!

**Comment by Keats** [comment]
I didn't think anyone was using that crate!
I would definitely take a PR for that.

**Comment by chinedufn** [comment]
Haha I love this crate! Been using it for years.

Awesome thanks. I'll submit a patch.
