### ISSUE TITLE
creating a migration requires a database connection

### ISSUE THREAD

**Issue by sbditto85** [Keats/dbmigrate#9]
Why does creating 2 files require a database connection? It isn't running them.

Really like what you've done so far. Keep up the great work!

**Comment by Keats** [comment]
Just simplicity, I could move the creation of file handler before checking for db data in `main.rs` actually

**Comment by Keats** [comment]
It would make sense to put it before but the code actually, I'll do it when i have time (or welcome a PR!)

**Comment by Keats** [comment]
https://github.com/Keats/dbmigrate/pull/10 should fix that

**Comment by Keats** [comment]
@sbditto85 it's in v0.2.4, sorry for the lateness completely forgot about it
